// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbchlnmjqqmyaenjiioi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiY2hsbm1qcXFteWFlbmppaW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODEyOTQsImV4cCI6MjA3MDQ1NzI5NH0.Hpq6MqRHQheikn4s2V8MUClujuXBU2l7AnqyDCGZrY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});